# Generated by Django 4.1.1 on 2022-09-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_rename_state_order_city_order_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="pincode",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Accepted", "Accepted"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
