# Generated by Django 4.1.1 on 2022-10-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Completed", "Completed"),
                    ("Canceled", "Canceled"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
