# Generated by Django 4.1.1 on 2022-10-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_alter_order_created_at_alter_orderproduct_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
