# Generated by Django 4.1.1 on 2022-10-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_order_offer_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="offer_status",
            field=models.BooleanField(default=False),
        ),
    ]
