# Generated by Django 4.1.1 on 2022-09-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
