# Generated by Django 4.1.1 on 2022-09-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_wishlist_wishlistitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistitems',
            name='wish_list',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
        migrations.DeleteModel(
            name='WishListItems',
        ),
    ]
