# Generated by Django 4.1.1 on 2022-10-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_coupon_usedcoupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="Brand_offer",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="category_offer",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="product_offer",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                    ),
                ),
            ],
        ),
    ]
