# Generated by Django 4.1.1 on 2022-10-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_brand_brand_offer_category_category_offer_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Offer",
            new_name="Offers",
        ),
    ]
