# Generated by Django 4.1.1 on 2022-10-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_offers_brand_offer_offers_cat_offer_offers_is_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offers",
            old_name="brand_offer",
            new_name="bran_offer",
        ),
        migrations.RenameField(
            model_name="offers",
            old_name="product_offer",
            new_name="pro_offer",
        ),
    ]
