# Generated by Django 4.1.1 on 2022-09-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_date_joined_alter_account_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
